# Generated by Django 5.0.4 on 2024-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
