# Generated by Django 5.0.4 on 2024-10-28 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
                ('Type', models.CharField(blank=True, choices=[('expense', 'expense'), ('credit', 'credit')], max_length=150, null=True)),
                ('Category', models.CharField(blank=True, choices=[('Food', 'Food'), ('Salary', 'Salary'), ('Utilities', 'Utilities'), ('Others', 'Others')], max_length=150, null=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
